In [66]:
import pandas as pd
import yaml
import functions

with open("../config.yaml") as file:
    config = yaml.safe_load(file)

{'input_data': {'file1': '../data/raw/df_final_demo.txt',
  'file2': '../data/raw/df_final_experiment_clients.txt',
  'file3': '../data/raw/df_final_web_data_pt_1.txt',
  'file4': '../data/raw/df_final_web_data_pt_2.txt'},
 'output_data': {'file1': None}}

In [11]:
df_final_experiment_clients = pd.read_csv(config["input_data"]["file2"])
df_final_experiment_clients.head()
df_final_experiment_clients["Variation"].value_counts()
df_final_experiment_clients.isna().sum()

client_id        0
Variation    20109
dtype: int64

In [67]:
df_final_demo = pd.read_csv(config["input_data"]["file1"])
df_final_demo.head()
#df_final_demo .info()
#df_final_demo .shape

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0

In [68]:
df_final_demo .info()

<class 'pandas.DataFrame'>
RangeIndex: 70609 entries, 0 to 70608
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   client_id         70609 non-null  int64
 1   clnt_tenure_yr    70595 non-null  float64
 2   clnt_tenure_mnth  70595 non-null  float64
 3   clnt_age          70594 non-null  float64
 4   gendr             70595 non-null  str
 5   num_accts         70595 non-null  float64
 6   bal               70595 non-null  float64
 7   calls_6_mnth      70595 non-null  float64
 8   logons_6_mnth     70595 non-null  float64
dtypes: float64(7), int64(1), str(1)
memory usage: 4.8 MB

In [98]:
def clean_final_demo_func(df_final_demo):
    """
    cleans df_final_demo.txt and outputs df_final_demo_cleaned.csv
    """
    df = df_final_demo.copy()
    #drop empty rows
    df = df.dropna(subset = "clnt_tenure_yr", ignore_index = True)
    #replace the missing age value in  clnt_age F
    condition = df["gendr"] == "F"
    #female_df = df_final_demo[condition]
    mean_age_f = df[condition].clnt_age.mean()
    
    df['clnt_age'] = df.clnt_age.fillna(mean_age_f)
    
    return df
df1 = clean_final_demo_func(df_final_demo)
df1.to_csv("clean_final_demo.csv", index = False)
df1.head()

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0